### ISSUE TITLE
Impossible to post new message with latest version

### ISSUE THREAD

**Issue by floufille** [NodeBB/nodebb-plugin-composer-quill#246]
NodeBB version: 1.18.6
Composer Quill version: 2.2.6

composer-redactor and composer-default are deactivated

(no issue with version 2.2.4)

When i'm trying to post a new message, i've this kind of error:
![image](https://user-images.githubusercontent.com/36710813/143758279-ac61edce-779f-457b-896a-d5398e449c35.png)

Invalid event: plugins.composer.getFormattingOptions

**Comment by barisusakli** [comment]
@julianlam as far as I can see there is no getFormattingOptions method in quill composer, that function exists only in composer-default server side.

**Comment by julianlam** [comment]
Hm... can't reproduce right now, I'm able to post new topics and chat with no issues. Will look into this `getFormattingOptions` call and see...

**Comment by floufille** [comment]
> ./nodebb plugins

Here the result of the command:

`xnodebb@lmtqa:/data/nodebb/repository$ ./nodebb plugins
2021-11-29T17:17:11.075Z [4567/30173] - verbose: [minifier] utilizing a maximum of 0 additional threads
Active plugins:
        * nodebb-plugin-composer-default@7.0.14 (installed, disabled)
        * nodebb-plugin-composer-quill@2.2.6 (installed, enabled)
        * nodebb-plugin-composer-redactor@3.5.5 (installed, disabled)
        * nodebb-plugin-dbsearch@5.1.0 (installed, disabled)
        * nodebb-plugin-emoji@3.5.3 (installed, disabled)
        * nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
        * nodebb-plugin-markdown@8.14.4 (installed, enabled)
        * nodebb-plugin-mentions@3.0.2 (installed, enabled)
        * nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
        * nodebb-plugin-spam-be-gone@0.7.11 (installed, enabled)
        * nodebb-rewards-essentials@0.2.0 (installed, enabled)
        * nodebb-theme-lavender@5.3.1 (installed, disabled)
        * nodebb-theme-persona@11.2.21 (installed, enabled)
        * nodebb-theme-slick@1.4.16 (installed, disabled)
        * nodebb-theme-vanilla@12.1.9 (installed, disabled)
        * nodebb-widget-essentials@5.0.4 (installed, enabled)`

**Comment by julianlam** [comment]
Can you let me know what version of composer-quill _does_ work?

**Comment by floufille** [comment]
The version 2.2.4 was OK (i didn't try the 2.2.5)

**Comment by julianlam** [comment]
Any server side errors on startup?

**Comment by floufille** [comment]
I have this error:

2021-11-28T09:15:23.891Z [4567/9386] - info: Initializing NodeBB v1.18.6 https://*****
2021-11-28T09:15:40.243Z [4567/9386] - info: [socket.io] Restricting access to origin: https://******
2021-11-28T09:15:43.924Z [4567/9386] - warn:    [plugins/nodebb-plugin-composer-quill] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2021-11-28T09:15:43.927Z [4567/9386] - warn: [plugins] Unable to load library for: nodebb-plugin-composer-quill
2021-11-28T09:15:43.927Z [4567/9386] - error: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /data/nodebb/repository/node_modules/is-html/index.js
require() of ES modules is not supported.
require() of /data/nodebb/repository/node_modules/is-html/index.js from /data/nodebb/repository/node_modules/nodebb-plugin-composer-quill/lib/migrator.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /data/nodebb/repository/node_modules/is-html/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/data/nodebb/repository/node_modules/nodebb-plugin-composer-quill/lib/migrator.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

2021-11-28T09:15:44.518Z [4567/9386] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-emoji

2021-11-28T09:15:44.851Z [4567/9386] - info: [plugins/spam-be-gone] Settings loaded
2021-11-28T09:15:45.065Z [4567/9386] - info: [api] Adding 0 route(s) to `api/v3/plugins`
2021-11-28T09:15:45.107Z [4567/9386] - info: [router] Routes added
2021-11-28T09:15:45.112Z [4567/9386] - info: NodeBB Ready
2021-11-28T09:15:45.114Z [4567/9386] - info: Enabling 'trust proxy'
2021-11-28T09:15:45.116Z [4567/9386] - info: NodeBB is now listening on: 0.0.0.0:4567

**Comment by julianlam** [comment]
Ah, got it. One second.

**Comment by julianlam** [comment]
Use v2.3.0 please.

**Comment by julianlam** [comment]
Closed via 110f116024e637ddd0fd5bd4337a9ef542688a3e

**Comment by floufille** [comment]
I just see this package can be updated, is there a way to force plugin version refresh ?

````
xnodebb@lmtqa:/data/nodebb/repository$ ./nodebb upgrade

Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started
npm WARN textcomplete.contenteditable@0.1.1 requires a peer of textcomplete@^0.14.2 but none is installed. You must install peer dependencies yourself.

audited 1300 packages in 17.672s

56 packages are looking for funding
  run `npm fund` for details

found 15 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

3. Checking installed plugins for updates...Checking installed plugins and themes for updates...   OK

A total of 1 package(s) can be upgraded:

  * nodebb-plugin-soundpack-default (1.0.0 -> 2.0.0)

Proceed with upgrade (y|n)? y

Upgrading packages...
````

**Comment by julianlam** [comment]
Not until it makes its way into nbbpm, but you can just install it via `npm` with `npm install nodebb-plugin-composer-quill@2.3.0`

**Comment by floufille** [comment]
Cool, that is working. Thanks
