### ISSUE TITLE
BUG: @textcomplete dropdown mentions and emojis not working on mouse click

### ISSUE THREAD

**Issue by cisnerosebastian** [NodeBB/nodebb-plugin-composer-quill#341]
Since nodebb update 2.6.1 (it has updates on composer default and new @textcomplete plugin) mentions and emjis dropdown item on click not working. Its working just fine if selected with keyboard and "enter" key. Its working perfect on composer default, but not on quill composer. When you click with mouse button, the composer content area scrolls up, and no autofill is done.

![image](https://user-images.githubusercontent.com/938368/208685999-221559ec-63d4-48da-8ecb-1c853fb86961.png)

I've installed a clean new nodebb 2.6.1 , quill 3.0.2 and its not working
also updated nodebb to 2.7.0 and still not working
then unistalled quill, and used composer default, and its working just fine

**Comment by barisusakli** [comment]
Looks bugged, I also get this error in the browser console sometimes

```
Uncaught Error: Unexpected
    at ContenteditableEditor.getRange (ContenteditableEditor.js:113:19)
    at ContenteditableEditor.getRange (ContenteditableEditor.js:117:28)
    at ContenteditableEditor.getBeforeCursor (ContenteditableEditor.js:86:28)
    at ContenteditableEditor.emitChangeEvent (Editor.js:71:36)
    at ContenteditableEditor.onInput (ContenteditableEditor.js:11:18)
```

**Comment by Incryve** [comment]
Hi there @barisusakli ! I was wondering if there has been a fix to this issue yet. My users keep drawing my attention to it and I'm hoping to address the problem asap. Thank you very much!

**Comment by barisusakli** [comment]
@Incryve nope, I tried to fix this but couldn't figure out the issue. Seems like textcomplete and quill don't play nice together. Selecting a option from the dropdown in textcomplete doesn't add the selected text into the quill composer.

**Comment by cisnerosebastian** [comment]
@barisusakli I may have some time to check on this issue. If you have any idea where the problem may be let me know.

**Comment by cisnerosebastian** [comment]
@barisusakli I've been trying to understand how this works. Its like quill is intercepting keyboard  and mouse events to update the quill contents and cursor. So, in this code

https://github.com/NodeBB/nodebb-plugin-composer-quill/blob/master/static/lib/quill-nbb.js#L362-L367

what is doing is like adding the tab and enter key events on the top of the list of quill events

maybe something similar is what we have to achieve with the mouse events?

On another hand, I can see that the textcomplete is actually getting the click event , and returning the right value, but that content is not been added on the quill contents. 

Anyway, I will try to spend more time on this next week.

**Comment by barisusakli** [comment]
Yeah that's what I found out too, when you click something in the dropdown that  text doesn't get inserted into the quill editor.

**Comment by cisnerosebastian** [comment]
Hi, it is me again. I'm still trying to fix this. So, I've made some progress, but still not 100% there yet.

This seeems more like missing functionallity than a bug.

in the default composer autocomplete.js there is a
